# Generated by Django 6.0.6 on 2026-06-11 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('ciclo_aberto', 'Ciclo aberto'), ('ciclo_fechado', 'Ciclo encerrado'), ('registro_enviado', 'Registro enviado'), ('validado_coord', 'Validado pelo coordenador'), ('validado_asplan', 'Validado pela ASPLAN')], max_length=30)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notificacao',
                'ordering': ['-criada_em'],
            },
        ),
    ]
