# Generated by Django 6.0.6 on 2026-06-10 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('quadrimestre', models.PositiveSmallIntegerField(choices=[(1, '1º Quadrimestre (Jan–Abr)'), (2, '2º Quadrimestre (Mai–Ago)'), (3, '3º Quadrimestre (Set–Dez)')])),
                ('dt_abertura', models.DateField()),
                ('dt_encerramento', models.DateField()),
                ('situacao', models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default='aberto', max_length=10)),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'db_table': 'ciclo',
                'ordering': ['-ano', '-quadrimestre'],
                'unique_together': {('ano', 'quadrimestre')},
            },
        ),
        migrations.CreateModel(
            name='ExecucaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='core.atividade')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='monitoramento.ciclo')),
            ],
            options={
                'verbose_name': 'Execução Financeira',
                'verbose_name_plural': 'Execuções Financeiras',
                'db_table': 'execucao_financeira',
                'unique_together': {('atividade', 'ciclo')},
            },
        ),
        migrations.CreateModel(
            name='RegistroQuadrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('problema', models.TextField(blank=True)),
                ('acao', models.TextField(blank=True)),
                ('analise', models.TextField(blank=True)),
                ('validado_coord', models.BooleanField(default=False)),
                ('validado_asplan', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='monitoramento.ciclo')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_criados', to=settings.AUTH_USER_MODEL)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.meta')),
            ],
            options={
                'verbose_name': 'Registro Quadrimestral',
                'verbose_name_plural': 'Registros Quadrimestrais',
                'db_table': 'registro_quad',
                'ordering': ['-ciclo__ano', '-ciclo__quadrimestre'],
                'unique_together': {('meta', 'ciclo')},
            },
        ),
    ]
