# Generated by Django 6.0.6 on 2026-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execucaofinanceira',
            options={'ordering': ['-ciclo__ano', '-ciclo__quadrimestre'], 'verbose_name': 'Execução Financeira', 'verbose_name_plural': 'Execuções Financeiras'},
        ),
        migrations.AddField(
            model_name='registroquadrimestral',
            name='atividades_nao_realizadas',
            field=models.TextField(blank=True),
        ),
    ]
