# Generated by Django 6.0.6 on 2026-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0002_alter_execucaofinanceira_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroquadrimestral',
            name='analise_indicadores',
            field=models.FileField(blank=True, null=True, upload_to='analise_indicadores/'),
        ),
    ]
