# Generated by Django 6.0.6 on 2026-06-15 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0003_registroquadrimestral_analise_indicadores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroquadrimestral',
            name='analise_indicadores',
        ),
        migrations.CreateModel(
            name='AnexoIndicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='analise_indicadores/')),
                ('nome_original', models.CharField(max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_indicadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anexo de Análise de Indicadores',
                'verbose_name_plural': 'Anexos de Análise de Indicadores',
                'db_table': 'anexo_indicadores',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
