# Generated by Django 6.0.6 on 2026-07-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoramento', '0004_remove_registroquadrimestral_analise_indicadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='pas_ano',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PAS'),
        ),
    ]
