# Generated by Django 6.0.6 on 2026-07-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_municipio'),
        ('monitoramento', '0005_add_pas_ano_to_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroquadrimestral',
            name='municipios_beneficiados',
            field=models.ManyToManyField(blank=True, db_table='registro_municipio', related_name='registros', to='core.municipio'),
        ),
    ]
