# Generated by Django 6.0.6 on 2026-07-09 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_popular_municipios'),
        ('monitoramento', '0006_add_municipios_beneficiados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('demandante', models.CharField(blank=True, max_length=255)),
                ('orgao_responsavel', models.CharField(blank=True, max_length=255)),
                ('unidade_auditada', models.CharField(blank=True, max_length=255)),
                ('finalidade', models.TextField(blank=True)),
                ('recomendacoes', models.TextField(blank=True)),
                ('encaminhamentos', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_criadas', to=settings.AUTH_USER_MODEL)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.meta')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='core.municipio')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
                'db_table': 'auditoria_sus',
                'ordering': ['ano', 'id'],
            },
        ),
    ]
