# Generated by Django 6.0.6 on 2026-06-10 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'area',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Diretriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('situacao', models.BooleanField(default=True)),
                ('ano', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Diretriz',
                'verbose_name_plural': 'Diretrizes',
                'db_table': 'diretriz',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('indicador', models.TextField(blank=True)),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('previsto_ppa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('previsto_exercicio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='core.area')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'db_table': 'meta',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.meta')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'db_table': 'atividade',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('diretriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='core.diretriz')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'db_table': 'objetivo',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='meta',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='core.objetivo'),
        ),
    ]
