# Generated by Django 6.0.6 on 2026-06-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='previsto_q1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='meta',
            name='previsto_q2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='meta',
            name='previsto_q3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
