# Generated by Django 6.0.6 on 2026-06-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meta_previsto_q1_meta_previsto_q2_meta_previsto_q3'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='indicador',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='unidade',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
