# Generated by Django 6.0.6 on 2026-06-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atividade_indicador_atividade_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
    ]
