# Generated by Django 6.0.6 on 2026-07-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_atividade_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
