# Generated by Django 6.0.6 on 2026-07-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_codigo_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ibge', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('regiao', models.CharField(max_length=100)),
                ('macrorregiao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'db_table': 'municipio',
                'ordering': ['macrorregiao', 'regiao', 'nome'],
            },
        ),
    ]
